apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: argo-cd
  namespace: argocd
spec:
  interval: 5m
  releaseName: argocd
  chart:
    spec:
      chart: argo-cd
      version: "7.1.*"
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
  install:
    createNamespace: true         # argocd ns is created for you
  values:
    configs:
      params:
        server.insecure: true      # sample override, adjust to taste
